// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0N44QpeO5CGREkQ_A9EMAC7ZTtFqThFQ',
    appId: '1:219774893710:web:d5e379982b4883fccc13df',
    messagingSenderId: '219774893710',
    projectId: 'push-notification-2025-73784',
    authDomain: 'push-notification-2025-73784.firebaseapp.com',
    storageBucket: 'push-notification-2025-73784.firebasestorage.app',
    measurementId: 'G-1S0DDGZK1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhJSMPlLo7yz-xuNjH-2Pjk7PNOcKgjBg',
    appId: '1:219774893710:android:6a7eff9414ca36fccc13df',
    messagingSenderId: '219774893710',
    projectId: 'push-notification-2025-73784',
    storageBucket: 'push-notification-2025-73784.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcsso_jEeGxvopoiaAcVjho9K2oeI4CjU',
    appId: '1:219774893710:ios:4520d7de5ae28d4dcc13df',
    messagingSenderId: '219774893710',
    projectId: 'push-notification-2025-73784',
    storageBucket: 'push-notification-2025-73784.firebasestorage.app',
    iosBundleId: 'com.example.gameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcsso_jEeGxvopoiaAcVjho9K2oeI4CjU',
    appId: '1:219774893710:ios:4520d7de5ae28d4dcc13df',
    messagingSenderId: '219774893710',
    projectId: 'push-notification-2025-73784',
    storageBucket: 'push-notification-2025-73784.firebasestorage.app',
    iosBundleId: 'com.example.gameApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0N44QpeO5CGREkQ_A9EMAC7ZTtFqThFQ',
    appId: '1:219774893710:web:32a768201f36ab6fcc13df',
    messagingSenderId: '219774893710',
    projectId: 'push-notification-2025-73784',
    authDomain: 'push-notification-2025-73784.firebaseapp.com',
    storageBucket: 'push-notification-2025-73784.firebasestorage.app',
    measurementId: 'G-5C7J6X7Y4E',
  );

}